/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function availableFormats(): Array<string>
export declare function getText(): Promise<string>
export declare function setText(text: string): Promise<void>
export declare function hasText(): boolean
export declare function getImageBinary(): Promise<Array<number>>
export declare function getImageBase64(): Promise<string>
export declare function setImageBinary(imageBytes: Array<number>): Promise<void>
export declare function setImageBase64(base64Str: string): Promise<void>
export declare function hasImage(): boolean
export declare function getHtml(): Promise<string>
export declare function setHtml(html: string): Promise<void>
export declare function hasHtml(): boolean
export declare function getRtf(): Promise<string>
export declare function setRtf(rtf: string): Promise<void>
export declare function hasRtf(): boolean
export declare function clear(): Promise<void>
export declare function watch(): void
export declare function callThreadsafeFunction(callback: (...args: any[]) => any): void
